use_frameworks!

target 'InverseTableView_Example' do
  pod 'InverseTableView', :path => '../'

  target 'InverseTableView_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.0"
    end
  end
end
